version: "3.1"

services:

  mysql:
    image: mysql:8.0
    container_name: db
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=simulados
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - "8082:3306"
    networks:
      - db
      - net

  php-fpm:
    container_name: php-fpm
    build: configs/php-fpm
    expose:
      - 9000
      - 9005
    volumes:
      - ./simulados-web:/application
      - ./configs/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      - ./configs/php-fpm/xdebug.ini:/etc/php/7.4/mods-available/xdebug.ini
    depends_on:
      - mysql
    networks:
      - db
  webserver:
    image: nginx:alpine
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./configs/nginx/logs:/var/log/nginx
    ports:
      - "8000:80"
      - "443:443"
    links:
      - php-fpm
    networks:
      - db
    depends_on:
      - php-fpm
      - mysql
  frontend:
    build: configs/frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/starter
    command:
      sh -c 'cp .env.example .env && npm i && npm run serve'
networks:
  net:
  db:
